#include <iostream>
#include <random>
#include <limits>
#include <cassert>
#include <chrono>
#include "ips4o.hpp"
#include "args.hxx"
#include "buffer.hpp"
#include "threads.hpp"
#include <endian.h>
#include "mmmultimap.hpp"

using namespace mmmultimap;

int main(int argc, char** argv) {

    args::ArgumentParser parser("memmapped multimap interface");
    args::HelpFlag help(parser, "help", "display this help summary", {'h', "help"});
    args::ValueFlag<std::string> in_file(parser, "FILE", "use this input file for a uint64_t sort", {'i', "in"});
    args::ValueFlag<std::string> test_file(parser, "FILE", "test mmmultimap with random data in this file", {'t', "test-file"});
    args::ValueFlag<uint64_t> test_size(parser, "N", "test this many pairs", {'s', "test-size"});
    args::ValueFlag<uint64_t> threads(parser, "N", "number of threads to use", {'t', "threads"});

    try {
        parser.ParseCLI(argc, argv);
    } catch (args::Help) {
        std::cout << parser;
        return 0;
    } catch (args::ParseError e) {
        std::cerr << e.what() << std::endl;
        std::cerr << parser;
        return 1;
    }
    if (argc==1) {
        std::cout << parser;
        return 1;
    }

    if (args::get(threads)) {
        omp_set_num_threads(args::get(threads));
    }
    
    if (!args::get(in_file).empty()) {
        mmap_buffer_t buffer;
        open_mmap_buffer(args::get(in_file).c_str(), &buffer);
        std::vector<uint64_t>::iterator begin_ptr((uint64_t*)buffer.data);
        uint64_t data_len = buffer.size/sizeof(uint64_t);
        std::vector<uint64_t>::iterator end_ptr((uint64_t*)buffer.data+data_len);
        std::cerr << "data length " << data_len << std::endl;

        std::cerr << "starting sort" << std::endl;
        auto start = std::chrono::system_clock::now();
        // sort in parallel (uses OpenMP if available, std::thread otherwise)
        ips4o::parallel::sort(begin_ptr, end_ptr);
        // sort sequentially
        //ips4o::sort(x.begin(), x.end());
        auto end = std::chrono::system_clock::now();

        std::chrono::duration<double> elapsed_seconds = end-start;
        std::time_t end_time = std::chrono::system_clock::to_time_t(end);
        std::cerr << "completed in " << elapsed_seconds.count() << "s" << std::endl;

        // check the sort
        /*
        std::cerr << "checking sort" << std::endl;
        uint64_t* x = (uint64_t*)buffer.data;
        for (int n=1; n<data_len; ++n) {
            assert(x[n-1] <= x[n]);
        }
        std::cerr << "ok" << std::endl;
        */

        close_mmap_buffer(&buffer);
    }

    if (!args::get(test_file).empty()) {
        std::random_device rd;  //Will be used to obtain a seed for the random number engine
        std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
        uint64_t max_key = args::get(test_size);
        std::uniform_int_distribution<uint64_t> dis(0, max_key);
        //std::vector<uint64_t> x; x.reserve(1e8);
        multimap<uint64_t, uint64_t> mm(args::get(test_file));
        uint64_t x_len = max_key;
#pragma omp parallel for
        for (int n=0; n<x_len; ++n) {
            //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
            mm.append(dis(gen), dis(gen));
        }
        mm.index(max_key);
        uint64_t i = 0;
        uint64_t key_count = 0;
        uint64_t value_count = 0;
        uint64_t unique_value_count = 0;
        bool first = true;
        uint64_t last = 0;
        mm.for_each_pair([&](uint64_t a, uint64_t b) {
                if (first || a > last) {
                    ++key_count;
                    last = a;
                    first = false;
                    mm.for_unique_values_of(a, [&](uint64_t v) {
                            ++unique_value_count;
                        });
                }
                ++value_count;
            });
        std::cerr << key_count << " keys" << std::endl;
        std::cerr << value_count << " values" << std::endl;
        std::cerr << unique_value_count << " unique pairs" << std::endl;
    }

    return 0;

}
